import logging
from datetime import datetime, timezone
from fpdf import FPDF
import io

logger = logging.getLogger("successcore.templates")

TEMPLATES = {
    "offer_letter": {
        "name": "Job Offer Letter",
        "fields": ["candidate_name", "position", "salary", "start_date", "company_name", "manager_name"],
    },
    "vacation_approval": {
        "name": "Vacation Approval Document",
        "fields": ["employee_name", "start_date", "end_date", "days", "approved_by"],
    },
    "expense_report": {
        "name": "Expense Report",
        "fields": ["employee_name", "period", "total_amount", "categories_summary", "approved_by"],
    },
}


def generate_pdf(template_name: str, data: dict) -> bytes:
    template = TEMPLATES.get(template_name)
    if not template:
        raise ValueError(f"Template '{template_name}' not found")

    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, template["name"], ln=True, align="C")
    pdf.ln(10)
    pdf.set_font("Helvetica", "", 11)

    for field in template["fields"]:
        value = data.get(field, "N/A")
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(60, 8, field.replace("_", " ").title() + ":")
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(0, 8, str(value), ln=True)

    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 9)
    pdf.cell(0, 8, f"Generated by SuccessCore HR on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}", ln=True, align="C")

    buf = io.BytesIO()
    pdf.output(buf)
    buf.seek(0)
    return buf.read()
