"""Add VisualWorkflow decoupled models

Revision ID: 616478ed8b62
Revises: df18a85ed333
Create Date: 2026-06-16 22:35:07.463093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '616478ed8b62'
down_revision: Union[str, Sequence[str], None] = 'df18a85ed333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visual_workflows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visual_workflows_agent_id'), 'visual_workflows', ['agent_id'], unique=False)
    op.create_index(op.f('ix_visual_workflows_tenant_id'), 'visual_workflows', ['tenant_id'], unique=False)
    op.add_column('workflow_steps', sa.Column('workflow_id', sa.String(), nullable=False))
    op.add_column('workflow_steps', sa.Column('next_nodes', sa.JSON(), nullable=False))
    op.add_column('workflow_steps', sa.Column('condition', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_workflow_steps_bot_id'), table_name='workflow_steps')
    op.create_index(op.f('ix_workflow_steps_workflow_id'), 'workflow_steps', ['workflow_id'], unique=False)
    op.drop_constraint(op.f('workflow_steps_bot_id_fkey'), 'workflow_steps', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_steps', 'visual_workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.drop_column('workflow_steps', 'bot_id')
    op.add_column('workflow_triggers', sa.Column('workflow_id', sa.String(), nullable=False))
    op.drop_index(op.f('ix_workflow_triggers_bot_id'), table_name='workflow_triggers')
    op.create_index(op.f('ix_workflow_triggers_workflow_id'), 'workflow_triggers', ['workflow_id'], unique=False)
    op.drop_constraint(op.f('workflow_triggers_bot_id_fkey'), 'workflow_triggers', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_triggers', 'visual_workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.drop_column('workflow_triggers', 'bot_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_triggers', sa.Column('bot_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workflow_triggers', type_='foreignkey')
    op.create_foreign_key(op.f('workflow_triggers_bot_id_fkey'), 'workflow_triggers', 'agents', ['bot_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_workflow_triggers_workflow_id'), table_name='workflow_triggers')
    op.create_index(op.f('ix_workflow_triggers_bot_id'), 'workflow_triggers', ['bot_id'], unique=False)
    op.drop_column('workflow_triggers', 'workflow_id')
    op.add_column('workflow_steps', sa.Column('bot_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workflow_steps', type_='foreignkey')
    op.create_foreign_key(op.f('workflow_steps_bot_id_fkey'), 'workflow_steps', 'agents', ['bot_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_workflow_steps_workflow_id'), table_name='workflow_steps')
    op.create_index(op.f('ix_workflow_steps_bot_id'), 'workflow_steps', ['bot_id'], unique=False)
    op.drop_column('workflow_steps', 'condition')
    op.drop_column('workflow_steps', 'next_nodes')
    op.drop_column('workflow_steps', 'workflow_id')
    op.drop_index(op.f('ix_visual_workflows_tenant_id'), table_name='visual_workflows')
    op.drop_index(op.f('ix_visual_workflows_agent_id'), table_name='visual_workflows')
    op.drop_table('visual_workflows')
    # ### end Alembic commands ###
