"""Add_RLS

Revision ID: f958538bcc19
Revises: add_roles_column_to_users
Create Date: 2026-06-15 18:31:24.100983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f958538bcc19'
down_revision: Union[str, Sequence[str], None] = 'add_roles_column_to_users'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('spent_amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_email', sa.String(length=200), nullable=False),
    sa.Column('customer_address', sa.String(length=500), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('line_items', sa.JSON(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_customer_invoices_tenant_id'), 'customer_invoices', ['tenant_id'], unique=False)
    op.create_table('hire_candidate_pools',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hire_candidate_pools_tenant_id'), 'hire_candidate_pools', ['tenant_id'], unique=False)
    op.create_table('pulse_surveys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pulse_surveys_tenant_id'), 'pulse_surveys', ['tenant_id'], unique=False)
    op.create_table('budget_lines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('budget_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('planned_amount', sa.Float(), nullable=False),
    sa.Column('actual_amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_lines_tenant_id'), 'budget_lines', ['tenant_id'], unique=False)
    op.create_table('ops_maintenance_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reported_by_id', sa.String(length=100), nullable=False),
    sa.Column('assigned_to_id', sa.String(length=100), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['ops_assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_maintenance_requests_tenant_id'), 'ops_maintenance_requests', ['tenant_id'], unique=False)
    op.create_table('workflow_steps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bot_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_steps_bot_id'), 'workflow_steps', ['bot_id'], unique=False)
    op.create_index(op.f('ix_workflow_steps_tenant_id'), 'workflow_steps', ['tenant_id'], unique=False)
    op.create_table('workflow_triggers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bot_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_triggers_bot_id'), 'workflow_triggers', ['bot_id'], unique=False)
    op.create_index(op.f('ix_workflow_triggers_tenant_id'), 'workflow_triggers', ['tenant_id'], unique=False)
    op.create_table('hire_candidate_pool_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pool_id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['hire_candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pool_id'], ['hire_candidate_pools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hire_candidate_pool_entries_tenant_id'), 'hire_candidate_pool_entries', ['tenant_id'], unique=False)
    op.create_table('pulse_responses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('survey_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['pulse_surveys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pulse_responses_tenant_id'), 'pulse_responses', ['tenant_id'], unique=False)
    op.create_table('grow_review_nominations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('review_id', sa.String(), nullable=True),
    sa.Column('nominator_id', sa.String(), nullable=True),
    sa.Column('nominee_id', sa.String(), nullable=True),
    sa.Column('relationship_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['nominator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['nominee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['grow_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grow_review_nominations_tenant_id'), 'grow_review_nominations', ['tenant_id'], unique=False)
    op.create_table('grow_review_responses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('review_id', sa.String(), nullable=True),
    sa.Column('reviewer_id', sa.String(), nullable=True),
    sa.Column('relationship_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('feedback', sa.JSON(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['grow_reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grow_review_responses_tenant_id'), 'grow_review_responses', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_comments_entity'), table_name='comments')
    op.drop_index(op.f('ix_comments_parent'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_user_integrations_user_id'), table_name='user_integrations')
    op.drop_table('user_integrations')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.add_column('agent_budget_caps', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_agent_budget_caps_tenant_id'), 'agent_budget_caps', ['tenant_id'], unique=False)
    op.add_column('agent_configs', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_agent_configs_tenant_id'), 'agent_configs', ['tenant_id'], unique=False)
    op.add_column('agent_event_trigger_configs', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_agent_event_trigger_configs_tenant_id'), 'agent_event_trigger_configs', ['tenant_id'], unique=False)
    op.add_column('agent_execution_runs', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_agent_execution_runs_tenant_id'), 'agent_execution_runs', ['tenant_id'], unique=False)
    op.add_column('agent_health_records', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_agent_health_records_tenant_id'), 'agent_health_records', ['tenant_id'], unique=False)
    op.add_column('agent_orchestration_runs', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_agent_orchestration_runs_tenant_id'), 'agent_orchestration_runs', ['tenant_id'], unique=False)
    op.add_column('agent_reputation_scores', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_agent_reputation_scores_tenant_id'), 'agent_reputation_scores', ['tenant_id'], unique=False)
    op.add_column('agent_schedules', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_agent_schedules_tenant_id'), 'agent_schedules', ['tenant_id'], unique=False)
    op.add_column('agent_sessions', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_agent_sessions_tenant_id'), 'agent_sessions', ['tenant_id'], unique=False)
    op.add_column('agent_trigger_queue', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_agent_trigger_queue_tenant_id'), 'agent_trigger_queue', ['tenant_id'], unique=False)
    op.add_column('agent_triggers', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_agent_triggers_tenant_id'), 'agent_triggers', ['tenant_id'], unique=False)
    op.add_column('agents', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.alter_column('agents', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('agents', 'marketplace_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'marketplace_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'marketplace_downloads',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'marketplace_tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('agents', 'marketplace_tools',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_index(op.f('ix_agents_tenant_id'), 'agents', ['tenant_id'], unique=False)
    op.add_column('announcements', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_announcements_tenant_id'), 'announcements', ['tenant_id'], unique=False)
    op.add_column('audit_logs', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.add_column('benchmark_runs', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_benchmark_runs_tenant_id'), 'benchmark_runs', ['tenant_id'], unique=False)
    op.add_column('branch_sessions', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_branch_sessions_tenant_id'), 'branch_sessions', ['tenant_id'], unique=False)
    op.add_column('break_logs', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_break_logs_tenant_id'), 'break_logs', ['tenant_id'], unique=False)
    op.add_column('chat_messages', sa.Column('parent_id', sa.String(), nullable=True))
    op.add_column('chat_messages', sa.Column('reactions', sa.JSON(), nullable=False))
    op.add_column('chat_messages', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_chat_messages_tenant_id'), 'chat_messages', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'chat_messages', 'chat_messages', ['parent_id'], ['id'], ondelete='SET NULL')
    op.add_column('chat_room_members', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_chat_room_members_tenant_id'), 'chat_room_members', ['tenant_id'], unique=False)
    op.add_column('chat_rooms', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_chat_rooms_tenant_id'), 'chat_rooms', ['tenant_id'], unique=False)
    op.add_column('code_modules', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_code_modules_tenant_id'), 'code_modules', ['tenant_id'], unique=False)
    op.add_column('collaborative_messages', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_collaborative_messages_tenant_id'), 'collaborative_messages', ['tenant_id'], unique=False)
    op.add_column('collaborative_room_participants', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_collaborative_room_participants_tenant_id'), 'collaborative_room_participants', ['tenant_id'], unique=False)
    op.add_column('collaborative_rooms', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_collaborative_rooms_tenant_id'), 'collaborative_rooms', ['tenant_id'], unique=False)
    op.add_column('conversation_epochs', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_conversation_epochs_tenant_id'), 'conversation_epochs', ['tenant_id'], unique=False)
    op.add_column('course_enrollments', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_course_enrollments_tenant_id'), 'course_enrollments', ['tenant_id'], unique=False)
    op.add_column('courses', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_courses_tenant_id'), 'courses', ['tenant_id'], unique=False)
    op.add_column('currency_rates', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.alter_column('currency_rates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_currency_rates_tenant_id'), 'currency_rates', ['tenant_id'], unique=False)
    op.add_column('demo_sessions', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_demo_sessions_tenant_id'), 'demo_sessions', ['tenant_id'], unique=False)
    op.add_column('demo_skills', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_demo_skills_tenant_id'), 'demo_skills', ['tenant_id'], unique=False)
    op.add_column('discovery_reports', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_discovery_reports_tenant_id'), 'discovery_reports', ['tenant_id'], unique=False)
    op.add_column('employee_history', sa.Column('employee_id', sa.String(), nullable=False))
    op.add_column('employee_history', sa.Column('field_name', sa.String(length=200), nullable=False))
    op.add_column('employee_history', sa.Column('old_value', sa.Text(), nullable=True))
    op.add_column('employee_history', sa.Column('new_value', sa.Text(), nullable=True))
    op.add_column('employee_history', sa.Column('changed_by', sa.String(), nullable=True))
    op.add_column('employee_history', sa.Column('changed_by_name', sa.String(length=200), nullable=True))
    op.add_column('employee_history', sa.Column('change_reason', sa.String(length=500), nullable=True))
    op.add_column('employee_history', sa.Column('source', sa.String(length=50), nullable=False))
    op.add_column('employee_history', sa.Column('metadata_json', sa.JSON(), nullable=False))
    op.add_column('employee_history', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.drop_index(op.f('ix_employee_history_user_id'), table_name='employee_history')
    op.create_index(op.f('ix_employee_history_employee_id'), 'employee_history', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_history_tenant_id'), 'employee_history', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('employee_history_user_id_fkey'), 'employee_history', type_='foreignkey')
    op.drop_column('employee_history', 'salary')
    op.drop_column('employee_history', 'end_date')
    op.drop_column('employee_history', 'start_date')
    op.drop_column('employee_history', 'position')
    op.drop_column('employee_history', 'user_id')
    op.drop_column('employee_history', 'department')
    op.drop_column('employee_history', 'currency')
    op.drop_column('employee_history', 'notes')
    op.add_column('episodic_memories', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_episodic_memories_tenant_id'), 'episodic_memories', ['tenant_id'], unique=False)
    op.add_column('expense_claims', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_expense_claims_tenant_id'), 'expense_claims', ['tenant_id'], unique=False)
    op.add_column('file_proposals', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_file_proposals_tenant_id'), 'file_proposals', ['tenant_id'], unique=False)
    op.add_column('fundae_validations', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_fundae_validations_tenant_id'), 'fundae_validations', ['tenant_id'], unique=False)
    op.add_column('general_shifts', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_general_shifts_tenant_id'), 'general_shifts', ['tenant_id'], unique=False)
    op.add_column('git_repositories', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_git_repositories_tenant_id'), 'git_repositories', ['tenant_id'], unique=False)
    op.add_column('grow_key_results', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_grow_key_results_tenant_id'), 'grow_key_results', ['tenant_id'], unique=False)
    op.add_column('grow_objectives', sa.Column('parent_id', sa.String(), nullable=True))
    op.add_column('grow_objectives', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('grow_objectives', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_grow_objectives_tenant_id'), 'grow_objectives', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'grow_objectives', 'grow_objectives', ['parent_id'], ['id'])
    op.add_column('grow_reviews', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_grow_reviews_tenant_id'), 'grow_reviews', ['tenant_id'], unique=False)
    op.add_column('hire_candidates', sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('hire_candidates', sa.Column('engagement_score', sa.Float(), nullable=False))
    op.add_column('hire_candidates', sa.Column('source_detail', sa.String(length=200), nullable=True))
    op.add_column('hire_candidates', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_hire_candidates_tenant_id'), 'hire_candidates', ['tenant_id'], unique=False)
    op.add_column('hire_interviews', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_hire_interviews_tenant_id'), 'hire_interviews', ['tenant_id'], unique=False)
    op.add_column('hire_jobs', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_hire_jobs_tenant_id'), 'hire_jobs', ['tenant_id'], unique=False)
    op.add_column('human_approval_requests', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_human_approval_requests_tenant_id'), 'human_approval_requests', ['tenant_id'], unique=False)
    op.add_column('intel_dashboards', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_intel_dashboards_tenant_id'), 'intel_dashboards', ['tenant_id'], unique=False)
    op.add_column('intel_kpi_alerts', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_intel_kpi_alerts_tenant_id'), 'intel_kpi_alerts', ['tenant_id'], unique=False)
    op.add_column('intel_widgets', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_intel_widgets_tenant_id'), 'intel_widgets', ['tenant_id'], unique=False)
    op.alter_column('invoices', 'type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'payable'::character varying"))
    op.alter_column('invoices', 'vendor_client',
               existing_type=sa.VARCHAR(length=200),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('invoices', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('invoices', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('invoices', 'tax_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('invoices', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'EUR'::character varying"))
    op.alter_column('invoices', 'exchange_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'1'::double precision"))
    op.alter_column('invoices', 'base_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('invoices', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'default'::character varying"))
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('it_assets', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_it_assets_tenant_id'), 'it_assets', ['tenant_id'], unique=False)
    op.add_column('it_kb_articles', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_it_kb_articles_tenant_id'), 'it_kb_articles', ['tenant_id'], unique=False)
    op.add_column('it_requisitions', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_it_requisitions_tenant_id'), 'it_requisitions', ['tenant_id'], unique=False)
    op.add_column('it_tickets', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_it_tickets_tenant_id'), 'it_tickets', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'it_tickets', 'users', ['solved_by'], ['id'], ondelete='SET NULL')
    op.add_column('journal_entries', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_journal_entries_tenant_id'), 'journal_entries', ['tenant_id'], unique=False)
    op.add_column('journal_lines', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_journal_lines_tenant_id'), 'journal_lines', ['tenant_id'], unique=False)
    op.add_column('knowledge_chunks', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.alter_column('knowledge_chunks', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_tenant_id'), 'knowledge_chunks', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'knowledge_chunks', 'knowledge_documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.add_column('knowledge_documents', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_knowledge_documents_tenant_id'), 'knowledge_documents', ['tenant_id'], unique=False)
    op.add_column('kudos', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_kudos_tenant_id'), 'kudos', ['tenant_id'], unique=False)
    op.add_column('legal_compliance_audits', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_legal_compliance_audits_tenant_id'), 'legal_compliance_audits', ['tenant_id'], unique=False)
    op.add_column('legal_contracts', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_legal_contracts_tenant_id'), 'legal_contracts', ['tenant_id'], unique=False)
    op.add_column('legal_dsar_tickets', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_legal_dsar_tickets_tenant_id'), 'legal_dsar_tickets', ['tenant_id'], unique=False)
    op.add_column('legal_whistleblower_reports', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_legal_whistleblower_reports_tenant_id'), 'legal_whistleblower_reports', ['tenant_id'], unique=False)
    op.add_column('llm_call_audits', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_llm_call_audits_tenant_id'), 'llm_call_audits', ['tenant_id'], unique=False)
    op.add_column('meetings', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_meetings_tenant_id'), 'meetings', ['tenant_id'], unique=False)
    op.add_column('model_performance', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_model_performance_tenant_id'), 'model_performance', ['tenant_id'], unique=False)
    op.add_column('notifications', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.add_column('ops_assets', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_ops_assets_tenant_id'), 'ops_assets', ['tenant_id'], unique=False)
    op.add_column('ops_bookings', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_ops_bookings_tenant_id'), 'ops_bookings', ['tenant_id'], unique=False)
    op.add_column('ops_visitors', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_ops_visitors_tenant_id'), 'ops_visitors', ['tenant_id'], unique=False)
    op.add_column('page_metadata', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_page_metadata_tenant_id'), 'page_metadata', ['tenant_id'], unique=False)
    op.add_column('pay_bonuses', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_pay_bonuses_tenant_id'), 'pay_bonuses', ['tenant_id'], unique=False)
    op.add_column('pay_cycles', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_pay_cycles_tenant_id'), 'pay_cycles', ['tenant_id'], unique=False)
    op.add_column('pay_payslip_lines', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_pay_payslip_lines_tenant_id'), 'pay_payslip_lines', ['tenant_id'], unique=False)
    op.add_column('pay_payslips', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_pay_payslips_tenant_id'), 'pay_payslips', ['tenant_id'], unique=False)
    op.add_column('pay_tax_rules', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_pay_tax_rules_tenant_id'), 'pay_tax_rules', ['tenant_id'], unique=False)
    op.add_column('permissions', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_permissions_tenant_id'), 'permissions', ['tenant_id'], unique=False)
    op.add_column('profile_change_requests', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_profile_change_requests_tenant_id'), 'profile_change_requests', ['tenant_id'], unique=False)
    op.add_column('prompt_versions', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_prompt_versions_tenant_id'), 'prompt_versions', ['tenant_id'], unique=False)
    op.add_column('role_permissions', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_role_permissions_tenant_id'), 'role_permissions', ['tenant_id'], unique=False)
    op.add_column('roles', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.add_column('saas_licenses', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_saas_licenses_tenant_id'), 'saas_licenses', ['tenant_id'], unique=False)
    op.add_column('sales_clients', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_sales_clients_tenant_id'), 'sales_clients', ['tenant_id'], unique=False)
    op.add_column('sales_leads', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_sales_leads_tenant_id'), 'sales_leads', ['tenant_id'], unique=False)
    op.add_column('shared_context_entries', sa.Column('tenant_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_shared_context_entries_orchestration_id'), 'shared_context_entries', ['orchestration_id'], unique=False)
    op.create_foreign_key(None, 'shared_context_entries', 'agents', ['agent_id'], ['id'])
    op.drop_column('shared_context_entries', 'embedding')
    op.add_column('skill_certifications', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_skill_certifications_tenant_id'), 'skill_certifications', ['tenant_id'], unique=False)
    op.add_column('skill_profiles', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_skill_profiles_tenant_id'), 'skill_profiles', ['tenant_id'], unique=False)
    op.add_column('tasks', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_tasks_tenant_id'), 'tasks', ['tenant_id'], unique=False)
    op.add_column('team_members', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_team_members_tenant_id'), 'team_members', ['tenant_id'], unique=False)
    op.add_column('teams', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_teams_tenant_id'), 'teams', ['tenant_id'], unique=False)
    op.add_column('test_cases', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_test_cases_tenant_id'), 'test_cases', ['tenant_id'], unique=False)
    op.add_column('test_runs', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_test_runs_tenant_id'), 'test_runs', ['tenant_id'], unique=False)
    op.add_column('test_suites', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_test_suites_tenant_id'), 'test_suites', ['tenant_id'], unique=False)
    op.add_column('time_logs', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_time_logs_tenant_id'), 'time_logs', ['tenant_id'], unique=False)
    op.add_column('user_memory_preferences', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_user_memory_preferences_tenant_id'), 'user_memory_preferences', ['tenant_id'], unique=False)
    op.add_column('user_workflows', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_user_workflows_tenant_id'), 'user_workflows', ['tenant_id'], unique=False)
    op.add_column('users', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.alter_column('users', 'roles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text('\'["employee"]\'::jsonb'))
    op.alter_column('users', 'vacation_allowance',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('30'))
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'Europe/Madrid'::character varying"))
    op.alter_column('users', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'EUR'::character varying"))
    op.alter_column('users', 'locale',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'es'::character varying"))
    op.alter_column('users', 'custom_fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'users', 'users', ['manager_id'], ['id'], ondelete='SET NULL')
    op.add_column('vacation_requests', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_vacation_requests_tenant_id'), 'vacation_requests', ['tenant_id'], unique=False)
    op.add_column('work_boards', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_work_boards_tenant_id'), 'work_boards', ['tenant_id'], unique=False)
    op.add_column('work_columns', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_work_columns_tenant_id'), 'work_columns', ['tenant_id'], unique=False)
    op.add_column('work_projects', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_work_projects_tenant_id'), 'work_projects', ['tenant_id'], unique=False)
    op.add_column('work_schedules', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_work_schedules_tenant_id'), 'work_schedules', ['tenant_id'], unique=False)
    op.add_column('work_sprints', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_work_sprints_tenant_id'), 'work_sprints', ['tenant_id'], unique=False)
    op.add_column('work_tasks', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_work_tasks_tenant_id'), 'work_tasks', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'work_tasks', 'work_sprints', ['sprint_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'work_tasks', 'work_columns', ['column_id'], ['id'], ondelete='SET NULL')
    op.add_column('work_wiki_pages', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_work_wiki_pages_tenant_id'), 'work_wiki_pages', ['tenant_id'], unique=False)
    op.add_column('workflow_templates', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_workflow_templates_tenant_id'), 'workflow_templates', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    # --- Add RLS Policies ---
    from app.models.base import Base
    for table_name in Base.metadata.tables.keys():
        op.execute(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation_policy ON {table_name};")
        op.execute(
            f"CREATE POLICY tenant_isolation_policy ON {table_name} "
            f"AS PERMISSIVE FOR ALL "
            f"TO PUBLIC "
            f"USING (tenant_id = current_setting('app.current_tenant_id', true));"
        )
        op.execute(f"ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY;")


def downgrade() -> None:
    """Downgrade schema."""
    # --- Remove RLS Policies ---
    from app.models.base import Base
    for table_name in Base.metadata.tables.keys():
        op.execute(f"ALTER TABLE {table_name} NO FORCE ROW LEVEL SECURITY;")
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation_policy ON {table_name};")
        op.execute(f"ALTER TABLE {table_name} DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_templates_tenant_id'), table_name='workflow_templates')
    op.drop_column('workflow_templates', 'tenant_id')
    op.drop_index(op.f('ix_work_wiki_pages_tenant_id'), table_name='work_wiki_pages')
    op.drop_column('work_wiki_pages', 'tenant_id')
    op.drop_constraint(None, 'work_tasks', type_='foreignkey')
    op.drop_constraint(None, 'work_tasks', type_='foreignkey')
    op.drop_index(op.f('ix_work_tasks_tenant_id'), table_name='work_tasks')
    op.drop_column('work_tasks', 'tenant_id')
    op.drop_index(op.f('ix_work_sprints_tenant_id'), table_name='work_sprints')
    op.drop_column('work_sprints', 'tenant_id')
    op.drop_index(op.f('ix_work_schedules_tenant_id'), table_name='work_schedules')
    op.drop_column('work_schedules', 'tenant_id')
    op.drop_index(op.f('ix_work_projects_tenant_id'), table_name='work_projects')
    op.drop_column('work_projects', 'tenant_id')
    op.drop_index(op.f('ix_work_columns_tenant_id'), table_name='work_columns')
    op.drop_column('work_columns', 'tenant_id')
    op.drop_index(op.f('ix_work_boards_tenant_id'), table_name='work_boards')
    op.drop_column('work_boards', 'tenant_id')
    op.drop_index(op.f('ix_vacation_requests_tenant_id'), table_name='vacation_requests')
    op.drop_column('vacation_requests', 'tenant_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.alter_column('users', 'custom_fields',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('users', 'locale',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'es'::character varying"))
    op.alter_column('users', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'EUR'::character varying"))
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'Europe/Madrid'::character varying"))
    op.alter_column('users', 'vacation_allowance',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('30'))
    op.alter_column('users', 'roles',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text('\'["employee"]\'::jsonb'))
    op.drop_column('users', 'tenant_id')
    op.drop_index(op.f('ix_user_workflows_tenant_id'), table_name='user_workflows')
    op.drop_column('user_workflows', 'tenant_id')
    op.drop_index(op.f('ix_user_memory_preferences_tenant_id'), table_name='user_memory_preferences')
    op.drop_column('user_memory_preferences', 'tenant_id')
    op.drop_index(op.f('ix_time_logs_tenant_id'), table_name='time_logs')
    op.drop_column('time_logs', 'tenant_id')
    op.drop_index(op.f('ix_test_suites_tenant_id'), table_name='test_suites')
    op.drop_column('test_suites', 'tenant_id')
    op.drop_index(op.f('ix_test_runs_tenant_id'), table_name='test_runs')
    op.drop_column('test_runs', 'tenant_id')
    op.drop_index(op.f('ix_test_cases_tenant_id'), table_name='test_cases')
    op.drop_column('test_cases', 'tenant_id')
    op.drop_index(op.f('ix_teams_tenant_id'), table_name='teams')
    op.drop_column('teams', 'tenant_id')
    op.drop_index(op.f('ix_team_members_tenant_id'), table_name='team_members')
    op.drop_column('team_members', 'tenant_id')
    op.drop_index(op.f('ix_tasks_tenant_id'), table_name='tasks')
    op.drop_column('tasks', 'tenant_id')
    op.drop_index(op.f('ix_skill_profiles_tenant_id'), table_name='skill_profiles')
    op.drop_column('skill_profiles', 'tenant_id')
    op.drop_index(op.f('ix_skill_certifications_tenant_id'), table_name='skill_certifications')
    op.drop_column('skill_certifications', 'tenant_id')
    op.add_column('shared_context_entries', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shared_context_entries', type_='foreignkey')
    op.drop_index(op.f('ix_shared_context_entries_orchestration_id'), table_name='shared_context_entries')
    op.drop_column('shared_context_entries', 'tenant_id')
    op.drop_index(op.f('ix_sales_leads_tenant_id'), table_name='sales_leads')
    op.drop_column('sales_leads', 'tenant_id')
    op.drop_index(op.f('ix_sales_clients_tenant_id'), table_name='sales_clients')
    op.drop_column('sales_clients', 'tenant_id')
    op.drop_index(op.f('ix_saas_licenses_tenant_id'), table_name='saas_licenses')
    op.drop_column('saas_licenses', 'tenant_id')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_column('roles', 'tenant_id')
    op.drop_index(op.f('ix_role_permissions_tenant_id'), table_name='role_permissions')
    op.drop_column('role_permissions', 'tenant_id')
    op.drop_index(op.f('ix_prompt_versions_tenant_id'), table_name='prompt_versions')
    op.drop_column('prompt_versions', 'tenant_id')
    op.drop_index(op.f('ix_profile_change_requests_tenant_id'), table_name='profile_change_requests')
    op.drop_column('profile_change_requests', 'tenant_id')
    op.drop_index(op.f('ix_permissions_tenant_id'), table_name='permissions')
    op.drop_column('permissions', 'tenant_id')
    op.drop_index(op.f('ix_pay_tax_rules_tenant_id'), table_name='pay_tax_rules')
    op.drop_column('pay_tax_rules', 'tenant_id')
    op.drop_index(op.f('ix_pay_payslips_tenant_id'), table_name='pay_payslips')
    op.drop_column('pay_payslips', 'tenant_id')
    op.drop_index(op.f('ix_pay_payslip_lines_tenant_id'), table_name='pay_payslip_lines')
    op.drop_column('pay_payslip_lines', 'tenant_id')
    op.drop_index(op.f('ix_pay_cycles_tenant_id'), table_name='pay_cycles')
    op.drop_column('pay_cycles', 'tenant_id')
    op.drop_index(op.f('ix_pay_bonuses_tenant_id'), table_name='pay_bonuses')
    op.drop_column('pay_bonuses', 'tenant_id')
    op.drop_index(op.f('ix_page_metadata_tenant_id'), table_name='page_metadata')
    op.drop_column('page_metadata', 'tenant_id')
    op.drop_index(op.f('ix_ops_visitors_tenant_id'), table_name='ops_visitors')
    op.drop_column('ops_visitors', 'tenant_id')
    op.drop_index(op.f('ix_ops_bookings_tenant_id'), table_name='ops_bookings')
    op.drop_column('ops_bookings', 'tenant_id')
    op.drop_index(op.f('ix_ops_assets_tenant_id'), table_name='ops_assets')
    op.drop_column('ops_assets', 'tenant_id')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_column('notifications', 'tenant_id')
    op.drop_index(op.f('ix_model_performance_tenant_id'), table_name='model_performance')
    op.drop_column('model_performance', 'tenant_id')
    op.drop_index(op.f('ix_meetings_tenant_id'), table_name='meetings')
    op.drop_column('meetings', 'tenant_id')
    op.drop_index(op.f('ix_llm_call_audits_tenant_id'), table_name='llm_call_audits')
    op.drop_column('llm_call_audits', 'tenant_id')
    op.drop_index(op.f('ix_legal_whistleblower_reports_tenant_id'), table_name='legal_whistleblower_reports')
    op.drop_column('legal_whistleblower_reports', 'tenant_id')
    op.drop_index(op.f('ix_legal_dsar_tickets_tenant_id'), table_name='legal_dsar_tickets')
    op.drop_column('legal_dsar_tickets', 'tenant_id')
    op.drop_index(op.f('ix_legal_contracts_tenant_id'), table_name='legal_contracts')
    op.drop_column('legal_contracts', 'tenant_id')
    op.drop_index(op.f('ix_legal_compliance_audits_tenant_id'), table_name='legal_compliance_audits')
    op.drop_column('legal_compliance_audits', 'tenant_id')
    op.drop_index(op.f('ix_kudos_tenant_id'), table_name='kudos')
    op.drop_column('kudos', 'tenant_id')
    op.drop_index(op.f('ix_knowledge_documents_tenant_id'), table_name='knowledge_documents')
    op.drop_column('knowledge_documents', 'tenant_id')
    op.drop_constraint(None, 'knowledge_chunks', type_='foreignkey')
    op.drop_index(op.f('ix_knowledge_chunks_tenant_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.alter_column('knowledge_chunks', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_column('knowledge_chunks', 'tenant_id')
    op.drop_index(op.f('ix_journal_lines_tenant_id'), table_name='journal_lines')
    op.drop_column('journal_lines', 'tenant_id')
    op.drop_index(op.f('ix_journal_entries_tenant_id'), table_name='journal_entries')
    op.drop_column('journal_entries', 'tenant_id')
    op.drop_constraint(None, 'it_tickets', type_='foreignkey')
    op.drop_index(op.f('ix_it_tickets_tenant_id'), table_name='it_tickets')
    op.drop_column('it_tickets', 'tenant_id')
    op.drop_index(op.f('ix_it_requisitions_tenant_id'), table_name='it_requisitions')
    op.drop_column('it_requisitions', 'tenant_id')
    op.drop_index(op.f('ix_it_kb_articles_tenant_id'), table_name='it_kb_articles')
    op.drop_column('it_kb_articles', 'tenant_id')
    op.drop_index(op.f('ix_it_assets_tenant_id'), table_name='it_assets')
    op.drop_column('it_assets', 'tenant_id')
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoices', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'default'::character varying"))
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('invoices', 'base_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('invoices', 'exchange_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'1'::double precision"))
    op.alter_column('invoices', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'EUR'::character varying"))
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('invoices', 'tax_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('invoices', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('invoices', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('invoices', 'vendor_client',
               existing_type=sa.VARCHAR(length=200),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('invoices', 'type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'payable'::character varying"))
    op.drop_index(op.f('ix_intel_widgets_tenant_id'), table_name='intel_widgets')
    op.drop_column('intel_widgets', 'tenant_id')
    op.drop_index(op.f('ix_intel_kpi_alerts_tenant_id'), table_name='intel_kpi_alerts')
    op.drop_column('intel_kpi_alerts', 'tenant_id')
    op.drop_index(op.f('ix_intel_dashboards_tenant_id'), table_name='intel_dashboards')
    op.drop_column('intel_dashboards', 'tenant_id')
    op.drop_index(op.f('ix_human_approval_requests_tenant_id'), table_name='human_approval_requests')
    op.drop_column('human_approval_requests', 'tenant_id')
    op.drop_index(op.f('ix_hire_jobs_tenant_id'), table_name='hire_jobs')
    op.drop_column('hire_jobs', 'tenant_id')
    op.drop_index(op.f('ix_hire_interviews_tenant_id'), table_name='hire_interviews')
    op.drop_column('hire_interviews', 'tenant_id')
    op.drop_index(op.f('ix_hire_candidates_tenant_id'), table_name='hire_candidates')
    op.drop_column('hire_candidates', 'tenant_id')
    op.drop_column('hire_candidates', 'source_detail')
    op.drop_column('hire_candidates', 'engagement_score')
    op.drop_column('hire_candidates', 'last_contacted_at')
    op.drop_index(op.f('ix_grow_reviews_tenant_id'), table_name='grow_reviews')
    op.drop_column('grow_reviews', 'tenant_id')
    op.drop_constraint(None, 'grow_objectives', type_='foreignkey')
    op.drop_index(op.f('ix_grow_objectives_tenant_id'), table_name='grow_objectives')
    op.drop_column('grow_objectives', 'tenant_id')
    op.drop_column('grow_objectives', 'department')
    op.drop_column('grow_objectives', 'parent_id')
    op.drop_index(op.f('ix_grow_key_results_tenant_id'), table_name='grow_key_results')
    op.drop_column('grow_key_results', 'tenant_id')
    op.drop_index(op.f('ix_git_repositories_tenant_id'), table_name='git_repositories')
    op.drop_column('git_repositories', 'tenant_id')
    op.drop_index(op.f('ix_general_shifts_tenant_id'), table_name='general_shifts')
    op.drop_column('general_shifts', 'tenant_id')
    op.drop_index(op.f('ix_fundae_validations_tenant_id'), table_name='fundae_validations')
    op.drop_column('fundae_validations', 'tenant_id')
    op.drop_index(op.f('ix_file_proposals_tenant_id'), table_name='file_proposals')
    op.drop_column('file_proposals', 'tenant_id')
    op.drop_index(op.f('ix_expense_claims_tenant_id'), table_name='expense_claims')
    op.drop_column('expense_claims', 'tenant_id')
    op.drop_index(op.f('ix_episodic_memories_tenant_id'), table_name='episodic_memories')
    op.drop_column('episodic_memories', 'tenant_id')
    op.add_column('employee_history', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('employee_history', sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('employee_history', sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('employee_history', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('employee_history', sa.Column('position', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('employee_history', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('employee_history', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('employee_history', sa.Column('salary', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('employee_history_user_id_fkey'), 'employee_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_employee_history_tenant_id'), table_name='employee_history')
    op.drop_index(op.f('ix_employee_history_employee_id'), table_name='employee_history')
    op.create_index(op.f('ix_employee_history_user_id'), 'employee_history', ['user_id'], unique=False)
    op.drop_column('employee_history', 'tenant_id')
    op.drop_column('employee_history', 'metadata_json')
    op.drop_column('employee_history', 'source')
    op.drop_column('employee_history', 'change_reason')
    op.drop_column('employee_history', 'changed_by_name')
    op.drop_column('employee_history', 'changed_by')
    op.drop_column('employee_history', 'new_value')
    op.drop_column('employee_history', 'old_value')
    op.drop_column('employee_history', 'field_name')
    op.drop_column('employee_history', 'employee_id')
    op.drop_index(op.f('ix_discovery_reports_tenant_id'), table_name='discovery_reports')
    op.drop_column('discovery_reports', 'tenant_id')
    op.drop_index(op.f('ix_demo_skills_tenant_id'), table_name='demo_skills')
    op.drop_column('demo_skills', 'tenant_id')
    op.drop_index(op.f('ix_demo_sessions_tenant_id'), table_name='demo_sessions')
    op.drop_column('demo_sessions', 'tenant_id')
    op.drop_index(op.f('ix_currency_rates_tenant_id'), table_name='currency_rates')
    op.alter_column('currency_rates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('currency_rates', 'tenant_id')
    op.drop_index(op.f('ix_courses_tenant_id'), table_name='courses')
    op.drop_column('courses', 'tenant_id')
    op.drop_index(op.f('ix_course_enrollments_tenant_id'), table_name='course_enrollments')
    op.drop_column('course_enrollments', 'tenant_id')
    op.drop_index(op.f('ix_conversation_epochs_tenant_id'), table_name='conversation_epochs')
    op.drop_column('conversation_epochs', 'tenant_id')
    op.drop_index(op.f('ix_collaborative_rooms_tenant_id'), table_name='collaborative_rooms')
    op.drop_column('collaborative_rooms', 'tenant_id')
    op.drop_index(op.f('ix_collaborative_room_participants_tenant_id'), table_name='collaborative_room_participants')
    op.drop_column('collaborative_room_participants', 'tenant_id')
    op.drop_index(op.f('ix_collaborative_messages_tenant_id'), table_name='collaborative_messages')
    op.drop_column('collaborative_messages', 'tenant_id')
    op.drop_index(op.f('ix_code_modules_tenant_id'), table_name='code_modules')
    op.drop_column('code_modules', 'tenant_id')
    op.drop_index(op.f('ix_chat_rooms_tenant_id'), table_name='chat_rooms')
    op.drop_column('chat_rooms', 'tenant_id')
    op.drop_index(op.f('ix_chat_room_members_tenant_id'), table_name='chat_room_members')
    op.drop_column('chat_room_members', 'tenant_id')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_index(op.f('ix_chat_messages_tenant_id'), table_name='chat_messages')
    op.drop_column('chat_messages', 'tenant_id')
    op.drop_column('chat_messages', 'reactions')
    op.drop_column('chat_messages', 'parent_id')
    op.drop_index(op.f('ix_break_logs_tenant_id'), table_name='break_logs')
    op.drop_column('break_logs', 'tenant_id')
    op.drop_index(op.f('ix_branch_sessions_tenant_id'), table_name='branch_sessions')
    op.drop_column('branch_sessions', 'tenant_id')
    op.drop_index(op.f('ix_benchmark_runs_tenant_id'), table_name='benchmark_runs')
    op.drop_column('benchmark_runs', 'tenant_id')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'tenant_id')
    op.drop_index(op.f('ix_announcements_tenant_id'), table_name='announcements')
    op.drop_column('announcements', 'tenant_id')
    op.drop_index(op.f('ix_agents_tenant_id'), table_name='agents')
    op.alter_column('agents', 'marketplace_tools',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('agents', 'marketplace_tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('agents', 'marketplace_downloads',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'marketplace_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'marketplace_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('agents', 'tenant_id')
    op.drop_index(op.f('ix_agent_triggers_tenant_id'), table_name='agent_triggers')
    op.drop_column('agent_triggers', 'tenant_id')
    op.drop_index(op.f('ix_agent_trigger_queue_tenant_id'), table_name='agent_trigger_queue')
    op.drop_column('agent_trigger_queue', 'tenant_id')
    op.drop_index(op.f('ix_agent_sessions_tenant_id'), table_name='agent_sessions')
    op.drop_column('agent_sessions', 'tenant_id')
    op.drop_index(op.f('ix_agent_schedules_tenant_id'), table_name='agent_schedules')
    op.drop_column('agent_schedules', 'tenant_id')
    op.drop_index(op.f('ix_agent_reputation_scores_tenant_id'), table_name='agent_reputation_scores')
    op.drop_column('agent_reputation_scores', 'tenant_id')
    op.drop_index(op.f('ix_agent_orchestration_runs_tenant_id'), table_name='agent_orchestration_runs')
    op.drop_column('agent_orchestration_runs', 'tenant_id')
    op.drop_index(op.f('ix_agent_health_records_tenant_id'), table_name='agent_health_records')
    op.drop_column('agent_health_records', 'tenant_id')
    op.drop_index(op.f('ix_agent_execution_runs_tenant_id'), table_name='agent_execution_runs')
    op.drop_column('agent_execution_runs', 'tenant_id')
    op.drop_index(op.f('ix_agent_event_trigger_configs_tenant_id'), table_name='agent_event_trigger_configs')
    op.drop_column('agent_event_trigger_configs', 'tenant_id')
    op.drop_index(op.f('ix_agent_configs_tenant_id'), table_name='agent_configs')
    op.drop_column('agent_configs', 'tenant_id')
    op.drop_index(op.f('ix_agent_budget_caps_tenant_id'), table_name='agent_budget_caps')
    op.drop_column('agent_budget_caps', 'tenant_id')
    op.create_table('push_subscriptions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('endpoint', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('keys', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('push_subscriptions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('push_subscriptions_pkey')),
    sa.UniqueConstraint('endpoint', name=op.f('push_subscriptions_endpoint_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('user_integrations',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('external_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('sync_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_sync_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_integrations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_integrations_pkey')),
    sa.UniqueConstraint('user_id', 'provider', name=op.f('uq_user_provider'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_integrations_user_id'), 'user_integrations', ['user_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_resolved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('comments_pkey'))
    )
    op.create_index(op.f('ix_comments_parent'), 'comments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_comments_entity'), 'comments', ['entity_type', 'entity_id'], unique=False)
    op.drop_index(op.f('ix_grow_review_responses_tenant_id'), table_name='grow_review_responses')
    op.drop_table('grow_review_responses')
    op.drop_index(op.f('ix_grow_review_nominations_tenant_id'), table_name='grow_review_nominations')
    op.drop_table('grow_review_nominations')
    op.drop_index(op.f('ix_pulse_responses_tenant_id'), table_name='pulse_responses')
    op.drop_table('pulse_responses')
    op.drop_index(op.f('ix_hire_candidate_pool_entries_tenant_id'), table_name='hire_candidate_pool_entries')
    op.drop_table('hire_candidate_pool_entries')
    op.drop_index(op.f('ix_workflow_triggers_tenant_id'), table_name='workflow_triggers')
    op.drop_index(op.f('ix_workflow_triggers_bot_id'), table_name='workflow_triggers')
    op.drop_table('workflow_triggers')
    op.drop_index(op.f('ix_workflow_steps_tenant_id'), table_name='workflow_steps')
    op.drop_index(op.f('ix_workflow_steps_bot_id'), table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index(op.f('ix_ops_maintenance_requests_tenant_id'), table_name='ops_maintenance_requests')
    op.drop_table('ops_maintenance_requests')
    op.drop_index(op.f('ix_budget_lines_tenant_id'), table_name='budget_lines')
    op.drop_table('budget_lines')
    op.drop_index(op.f('ix_pulse_surveys_tenant_id'), table_name='pulse_surveys')
    op.drop_table('pulse_surveys')
    op.drop_index(op.f('ix_hire_candidate_pools_tenant_id'), table_name='hire_candidate_pools')
    op.drop_table('hire_candidate_pools')
    op.drop_index(op.f('ix_customer_invoices_tenant_id'), table_name='customer_invoices')
    op.drop_table('customer_invoices')
    op.drop_table('budgets')
    # ### end Alembic commands ###
